# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, Optional

from .base_model import BaseModel


class DeleteSubscriptionsByPk(BaseModel):
    delete_subscriptions_by_pk: Optional[
        "DeleteSubscriptionsByPkDeleteSubscriptionsByPk"
    ]


class DeleteSubscriptionsByPkDeleteSubscriptionsByPk(BaseModel):
    id: Any
    email: str
    interval: str
    lat_min: Any
    lon_min: Any
    lat_max: Any
    lon_max: Any


DeleteSubscriptionsByPk.model_rebuild()
