# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Optional

from .base_model import BaseModel


class DeleteEntryTags(BaseModel):
    delete_entry_tags_by_pk: Optional["DeleteEntryTagsDeleteEntryTagsByPk"]


class DeleteEntryTagsDeleteEntryTagsByPk(BaseModel):
    entry: str
    tag: str


DeleteEntryTags.model_rebuild()
