# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, List

from .base_model import BaseModel


class GetExactSubscriptions(BaseModel):
    subscriptions: List["GetExactSubscriptionsSubscriptions"]


class GetExactSubscriptionsSubscriptions(BaseModel):
    id: Any


GetExactSubscriptions.model_rebuild()
