# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class GetActiveSubscriptionsByInterval(BaseModel):
    subscriptions: List["GetActiveSubscriptionsByIntervalSubscriptions"]


class GetActiveSubscriptionsByIntervalSubscriptions(BaseModel):
    email: str
    id: Any
    lat_min: Any
    lon_min: Any
    lat_max: Any
    lon_max: Any
    interval: str
    subscription_type: Any
    language: Optional[str]


GetActiveSubscriptionsByInterval.model_rebuild()
