# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, List

from .base_model import BaseModel


class GetSubscriptionsByInterval(BaseModel):
    subscriptions: List["GetSubscriptionsByIntervalSubscriptions"]


class GetSubscriptionsByIntervalSubscriptions(BaseModel):
    email: str
    id: Any
    lat_min: Any
    lon_min: Any
    lat_max: Any
    lon_max: Any
    interval: str
    subscription_type: Any


GetSubscriptionsByInterval.model_rebuild()
