# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from .base_model import BaseModel


class GetEntryTags(BaseModel):
    entry_tags: List["GetEntryTagsEntryTags"]


class GetEntryTagsEntryTags(BaseModel):
    tag: str


GetEntryTags.model_rebuild()
