# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Optional

from .base_model import BaseModel


class InsertEntryTags(BaseModel):
    insert_entry_tags: Optional["InsertEntryTagsInsertEntryTags"]


class InsertEntryTagsInsertEntryTags(BaseModel):
    affected_rows: int


InsertEntryTags.model_rebuild()
