# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Optional

from .base_model import BaseModel


class InsertEntries(BaseModel):
    insert_entries: Optional["InsertEntriesInsertEntries"]


class InsertEntriesInsertEntries(BaseModel):
    affected_rows: int


InsertEntries.model_rebuild()
