# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Optional

from .base_model import BaseModel


class InsertTags(BaseModel):
    insert_tags: Optional["InsertTagsInsertTags"]


class InsertTagsInsertTags(BaseModel):
    affected_rows: int


InsertTags.model_rebuild()
