[tool.ariadne-codegen]
queries_path = "queries.graphql"
remote_schema_url = "http://95.217.222.28:8787/v1/graphql"
remote_schema_verify_ssl = false
remote_schema_headers = {"x-hasura-admin-secret" = "HFyp3TNzjiwmNFt7TfxTcXsNbGbg5Jrd"}
